#ifndef __CONFIG__H__
#define __CONFIG__H__

#define LEVEL_SHIFTER_OE_PIN 7
#define LORA_WIRELESS_MODULE_M0_PIN 8
#define LORA_WIRELESS_MODULE_M1_PIN 9
#define SOFTWARE_SERIAL_TRANSMIT_PIN 10
#define SOFTWARE_SERIAL_RECEIVE_PIN 11
#define LORA_WIRELESS_MODULE_AUX_PIN 12

#endif // __CONFIG__H__