#ifndef CONFIG_H
#define CONFIG_H


#define LORA_MODULE_AUX_PIN 2
#define LORA_MODULE_RX_PIN 8
#define LORA_MODULE_TX_PIN 9
#define LORA_MODULE_M0_PIN 10
#define LORA_MODULE_M1_PIN 11
#define LEVEL_SHIFTER_OE_PIN 7


#endif // CONFIG_H